// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
/* eslint-disable */
const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:4c8108dc-8bc7-46eb-bb40-f625b05a8e8c",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_jVFMF9LT3",
    "aws_user_pools_web_client_id": "2nlf4qtujqi8ikfkol05feeen8",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://cdkqa2u4fvetxmo4eomzq7av3y.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
